In [57]:
struct ShipDirection{x} end;
ShipDirection(x) = ShipDirection{x}()
struct WaypointDirection{x} end;
WaypointDirection(x) = WaypointDirection{x}()

mutable struct ShipState
    facing::ShipDirection
    x::Int
    y::Int
end

mutable struct WaypointState
    x::Int
    y::Int
end

function get_instructions(filename)
    input = readlines(filename)
    instructions = map(input) do x
        instr = r"^([A-Z])([0-9]*)$"
        m = match(instr, x)
        (ShipDirection(Symbol(m[1])), parse(Int, m[2]))
    end
    instructions
end

# rotate right
function new_direction(facing::ShipDirection, d::ShipDirection{:R}, val)
    val % 90 != 0 && error("$(val) must be a multiple of 90")
    times = Int(val // 90)
    times > 4 && error("times direction cannot exceed 4")
    directions = [
        ShipDirection(:E),
        ShipDirection(:S),
        ShipDirection(:W),
        ShipDirection(:N),
        ShipDirection(:E),
        ShipDirection(:S),
        ShipDirection(:W),
        ShipDirection(:N)
    ]
    directions[findfirst(x -> x == facing, directions) + times]
end

# rotate left
function new_direction(facing::ShipDirection, d::ShipDirection{:L}, val)
    val % 90 != 0 && error("$(val) must be a multiple of 90")
    times = Int(val // 90)
    times > 4 && error("times direction cannot exceed 4")
    directions = [
        ShipDirection(:E),
        ShipDirection(:N),
        ShipDirection(:W),
        ShipDirection(:S),
        ShipDirection(:E),
        ShipDirection(:N),
        ShipDirection(:W),
        ShipDirection(:S)
    ]
    directions[findfirst(x -> x == facing, directions) + times]
end

new_position(facing::ShipDirection, d::ShipDirection{:E}, val) = [val, 0]
new_position(facing::ShipDirection, d::ShipDirection{:W}, val) = [-val, 0]
new_position(facing::ShipDirection, d::ShipDirection{:N}, val) = [0, val]
new_position(facing::ShipDirection, d::ShipDirection{:S}, val) = [0, -val]

new_position(facing::ShipDirection{:E}, d::ShipDirection{:F}, val) = [val, 0]
new_position(facing::ShipDirection{:W}, d::ShipDirection{:F}, val) = [-val, 0]
new_position(facing::ShipDirection{:N}, d::ShipDirection{:F}, val) = [0, val]
new_position(facing::ShipDirection{:S}, d::ShipDirection{:F}, val) = [0, -val]

function update!(s::ShipState, w::WaypointState, d::ShipDirection, val)
#     np = new_position(s.facing, d, val)
#     @show s, d, val
#     s.x += np[1]
#     s.y += np[2]
#     @show s, d, val
end

function update!(s::ShipState, w::WaypointState, d::ShipDirection{:F}, val)
    s.x += w.x * val
    s.y += w.y * val
end

function update!(s::ShipState, w::WaypointState, d::ShipDirection{:N}, val)
    w.y += val
end

function update!(s::ShipState, w::WaypointState, d::ShipDirection{:S}, val)
    w.y -= val
end

function update!(s::ShipState, w::WaypointState, d::ShipDirection{:E}, val)
    w.x += val
end

function update!(s::ShipState, w::WaypointState, d::ShipDirection{:W}, val)
    w.x -= val
end


function update!(s::ShipState, w::WaypointState, d::ShipDirection{:R}, val)
#     nd = new_direction(s.facing, d, val)
#     @show s, d, val, nd
#     s.facing = nd
end
function update!(s::ShipState, w::WaypointState, d::ShipDirection{:L}, val)
#     nd = new_direction(s.facing, d, val)
#     @show s, d, val, nd
#     s.facing = nd
end

update! (generic function with 8 methods)

In [78]:
function rotate_point(cx, cy, angle, px, py)
    s = sin(deg2rad(angle))
    c = cos(deg2rad(angle))
    px -= cx
    py -= cy
    xnew = px * c - py * s
    ynew = px * s + py * c
    px = xnew + cx
    py = ynew + cy
    [px, py]
end
rotate_point(10, 4, 90, 170, 38)

2-element Array{Float64,1}:
 -23.999999999999993
 164.0

In [86]:
# angle = (angle ) * (Math.PI/180); // Convert to radians
# var rotatedX = Math.cos(angle) * (point.x - center.x) - Math.sin(angle) * (point.y-center.y) + center.x;
# var rotatedY = Math.sin(angle) * (point.x - center.x) + Math.cos(angle) * (point.y - center.y) + center.y;
# return new createjs.Point(rotatedX,rotatedY);

function rotate_point(px, py, cx, cy, θ)
    θ = deg2rad(θ)
    rX = cos(θ) * (px - cx) - sin(θ) * (py - cy) + cx
    rY = sin(θ) * (px - cx) + cos(θ) * (py - cy) + cy
    [rX, rY]
end
rotate_point(170, 38, 90, 170+10, 38+4)

2-element Array{Float64,1}:
 244.4681321411494
 128.00388329091868

In [93]:
[170, 38] .* [10, 4]

2-element Array{Int64,1}:
 1700
  152

In [94]:
[10, 4] .* [170, 38]

2-element Array{Int64,1}:
 1700
  152

In [80]:
[10 10; 5 5]

2×2 Array{Int64,2}:
 10  10
  5   5

In [73]:
[170, 38] .+ [-24, 164]

2-element Array{Int64,1}:
 146
 202

In [62]:
?sin

search: sin sinh sind sinc sinpi sincos sincosd asin using isinf asinh asind



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
 0.454649  0.454649
 0.454649  0.454649
```


In [ ]:
POINT rotate_point(float cx,float cy,float angle,POINT p)
{
  float s = sin(angle);
  float c = cos(angle);

  // translate point back to origin:
  p.x -= cx;
  p.y -= cy;

  // rotate point
  float xnew = p.x * c - p.y * s;
  float ynew = p.x * s + p.y * c;

  // translate point back:
  p.x = xnew + cx;
  p.y = ynew + cy;
  return p;
}

In [58]:
shipState = ShipState(ShipDirection(:E), 0, 0);
waypointState = WaypointState(10, 1);
instr = get_instructions("input/day12-test.txt");
instr

5-element Array{Tuple{ShipDirection{_A} where _A,Int64},1}:
 (ShipDirection{:F}(), 10)
 (ShipDirection{:N}(), 3)
 (ShipDirection{:F}(), 7)
 (ShipDirection{:R}(), 90)
 (ShipDirection{:F}(), 11)

In [59]:
for (direction, val) in instr
     update!(shipState, waypointState, direction, val)
end

(s, w) = (ShipState(ShipDirection{:E}(), 0, 0), WaypointState(10, 1))
(s, w) = (ShipState(ShipDirection{:E}(), 100, 10), WaypointState(10, 1))
(s, w) = (ShipState(ShipDirection{:E}(), 170, 17), WaypointState(10, 1))


In [60]:
shipState

ShipState(ShipDirection{:E}(), 280, 28)

In [31]:
abs(shipState.x) + abs(shipState.y)

28