In [34]:
input = readlines("input/day13-test.txt")[2]
input = "17,x,13,19"
bus_cycles = [parse(Int, i == "x" ? "0" : i) for i in split.(input, ",")]
indices = collect(0:length(bus_cycles)-1);

In [35]:
maxidx = argmax(bus_cycles)
maxval = bus_cycles[maxidx]

19

In [36]:
maxidx

4

In [37]:
bus_cycles

4-element Array{Int64,1}:
 17
  0
 13
 19

In [40]:
additions = 0:length(bus_cycles)-1

0:3

In [41]:
additions|>collect

4-element Array{Int64,1}:
 0
 1
 2
 3

In [55]:
bus_cycles

4-element Array{Int64,1}:
 17
  0
 13
 19

In [56]:
additions

0:3

In [66]:
tuples = [(i, j) for (i, j) in zip(bus_cycles, additions) if i != 0]

3-element Array{Tuple{Int64,Int64},1}:
 (17, 0)
 (13, 2)
 (19, 3)

In [72]:
two_largest = sort(first.(tuples))[end-1:end]

2-element Array{Int64,1}:
 17
 19

In [73]:
largest_lcm = lcm(two_largest)

323

In [67]:
lcm(19, 17)

323

In [68]:
323 / 19

17.0

In [69]:
323 / 17

19.0

In [57]:
for (i, j) in zip(bus_cycles, additions)
    @show i, j
end

(i, j) = (17, 0)
(i, j) = (0, 1)
(i, j) = (13, 2)
(i, j) = (19, 3)


In [74]:
schedule = parse.(Int, replace(split("17,x,13,19", ","), "x" => "-1"))

bus_n = filter(!=(-1), schedule)
bus_dt = (1:length(schedule))[schedule .!= -1] .- 1

# part 2
function find_seq_bus_arrivals(bus_n, bus_dt)
    inc = bus_n[1] 
    n = 0
    for (i, offset) in zip(bus_n[2:end], bus_dt[2:end])
        while (n + offset) % i != 0
            n += inc
        end
        inc = lcm(inc, i)
    end
    return n
end

println(find_seq_bus_arrivals(bus_n, bus_dt))


3417


In [80]:
for (i, offset) in zip(bus_n[2:end], bus_dt[2:end])
    @show i, offset
end

(i, offset) = (13, 2)
(i, offset) = (19, 3)


In [54]:
l = length(bus_cycles)
i = 1
bingo = false
while !bingo
    bingo = true
    checkval = (maxval * i) + additions[maxidx]
    @show checkval
    for (jidx, addition) in enumerate(additions)
        bus_cycles[jidx] == 0 && continue
        if !(checkval % (bus_cycles[jidx] + addition) == 0)
            bingo = false
            break
        end
    end
    bingo && println(i) isa Nothing && break
    i >= 5000 && break
    i += 1
end

checkval = 22
checkval = 41
checkval = 60
checkval = 79
checkval = 98
checkval = 117
checkval = 136
checkval = 155
checkval = 174
checkval = 193
checkval = 212
checkval = 231
checkval = 250
checkval = 269
checkval = 288
checkval = 307
checkval = 326
checkval = 345
checkval = 364
checkval = 383
checkval = 402
checkval = 421
checkval = 440
checkval = 459
checkval = 478
checkval = 497
checkval = 516
checkval = 535
checkval = 554
checkval = 573
checkval = 592
checkval = 611
checkval = 630
checkval = 649
checkval = 668
checkval = 687
checkval = 706
checkval = 725
checkval = 744
checkval = 763
checkval = 782
checkval = 801
checkval = 820
checkval = 839
checkval = 858
checkval = 877
checkval = 896
checkval = 915
checkval = 934
checkval = 953
checkval = 972
checkval = 991
checkval = 1010
checkval = 1029
checkval = 1048
checkval = 1067
checkval = 1086
checkval = 1105
checkval = 1124
checkval = 1143
checkval = 1162
checkval = 1181
checkval = 1200
checkval = 1219
checkval = 1238
checkval = 1257
c

checkval = 12106
checkval = 12125
checkval = 12144
checkval = 12163
checkval = 12182
checkval = 12201
checkval = 12220
checkval = 12239
checkval = 12258
checkval = 12277
checkval = 12296
checkval = 12315
checkval = 12334
checkval = 12353
checkval = 12372
checkval = 12391
checkval = 12410
checkval = 12429
checkval = 12448
checkval = 12467
checkval = 12486
checkval = 12505
checkval = 12524
checkval = 12543
checkval = 12562
checkval = 12581
checkval = 12600
checkval = 12619
checkval = 12638
checkval = 12657
checkval = 12676
checkval = 12695
checkval = 12714
checkval = 12733
checkval = 12752
checkval = 12771
checkval = 12790
checkval = 12809
checkval = 12828
checkval = 12847
checkval = 12866
checkval = 12885
checkval = 12904
checkval = 12923
checkval = 12942
checkval = 12961
checkval = 12980
checkval = 12999
checkval = 13018
checkval = 13037
checkval = 13056
checkval = 13075
checkval = 13094
checkval = 13113
checkval = 13132
checkval = 13151
checkval = 13170
checkval = 13189
checkval = 132

checkval = 23563
checkval = 23582
checkval = 23601
checkval = 23620
checkval = 23639
checkval = 23658
checkval = 23677
checkval = 23696
checkval = 23715
checkval = 23734
checkval = 23753
checkval = 23772
checkval = 23791
checkval = 23810
checkval = 23829
checkval = 23848
checkval = 23867
checkval = 23886
checkval = 23905
checkval = 23924
checkval = 23943
checkval = 23962
checkval = 23981
checkval = 24000
checkval = 24019
checkval = 24038
checkval = 24057
checkval = 24076
checkval = 24095
checkval = 24114
checkval = 24133
checkval = 24152
checkval = 24171
checkval = 24190
checkval = 24209
checkval = 24228
checkval = 24247
checkval = 24266
checkval = 24285
checkval = 24304
checkval = 24323
checkval = 24342
checkval = 24361
checkval = 24380
checkval = 24399
checkval = 24418
checkval = 24437
checkval = 24456
checkval = 24475
checkval = 24494
checkval = 24513
checkval = 24532
checkval = 24551
checkval = 24570
checkval = 24589
checkval = 24608
checkval = 24627
checkval = 24646
checkval = 246

checkval = 35476
checkval = 35495
checkval = 35514
checkval = 35533
checkval = 35552
checkval = 35571
checkval = 35590
checkval = 35609
checkval = 35628
checkval = 35647
checkval = 35666
checkval = 35685
checkval = 35704
checkval = 35723
checkval = 35742
checkval = 35761
checkval = 35780
checkval = 35799
checkval = 35818
checkval = 35837
checkval = 35856
checkval = 35875
checkval = 35894
checkval = 35913
checkval = 35932
checkval = 35951
checkval = 35970
checkval = 35989
checkval = 36008
checkval = 36027
checkval = 36046
checkval = 36065
checkval = 36084
checkval = 36103
checkval = 36122
checkval = 36141
checkval = 36160
checkval = 36179
checkval = 36198
checkval = 36217
checkval = 36236
checkval = 36255
checkval = 36274
checkval = 36293
checkval = 36312
checkval = 36331
checkval = 36350
checkval = 36369
checkval = 36388
checkval = 36407
checkval = 36426
checkval = 36445
checkval = 36464
checkval = 36483
checkval = 36502
checkval = 36521
checkval = 36540
checkval = 36559
checkval = 365

checkval = 46933
checkval = 46952
checkval = 46971
checkval = 46990
checkval = 47009
checkval = 47028
checkval = 47047
checkval = 47066
checkval = 47085
checkval = 47104
checkval = 47123
checkval = 47142
checkval = 47161
checkval = 47180
checkval = 47199
checkval = 47218
checkval = 47237
checkval = 47256
checkval = 47275
checkval = 47294
checkval = 47313
checkval = 47332
checkval = 47351
checkval = 47370
checkval = 47389
checkval = 47408
checkval = 47427
checkval = 47446
checkval = 47465
checkval = 47484
checkval = 47503
checkval = 47522
checkval = 47541
checkval = 47560
checkval = 47579
checkval = 47598
checkval = 47617
checkval = 47636
checkval = 47655
checkval = 47674
checkval = 47693
checkval = 47712
checkval = 47731
checkval = 47750
checkval = 47769
checkval = 47788
checkval = 47807
checkval = 47826
checkval = 47845
checkval = 47864
checkval = 47883
checkval = 47902
checkval = 47921
checkval = 47940
checkval = 47959
checkval = 47978
checkval = 47997
checkval = 48016
checkval = 480

checkval = 58390
checkval = 58409
checkval = 58428
checkval = 58447
checkval = 58466
checkval = 58485
checkval = 58504
checkval = 58523
checkval = 58542
checkval = 58561
checkval = 58580
checkval = 58599
checkval = 58618
checkval = 58637
checkval = 58656
checkval = 58675
checkval = 58694
checkval = 58713
checkval = 58732
checkval = 58751
checkval = 58770
checkval = 58789
checkval = 58808
checkval = 58827
checkval = 58846
checkval = 58865
checkval = 58884
checkval = 58903
checkval = 58922
checkval = 58941
checkval = 58960
checkval = 58979
checkval = 58998
checkval = 59017
checkval = 59036
checkval = 59055
checkval = 59074
checkval = 59093
checkval = 59112
checkval = 59131
checkval = 59150
checkval = 59169
checkval = 59188
checkval = 59207
checkval = 59226
checkval = 59245
checkval = 59264
checkval = 59283
checkval = 59302
checkval = 59321
checkval = 59340
checkval = 59359
checkval = 59378
checkval = 59397
checkval = 59416
checkval = 59435
checkval = 59454
checkval = 59473
checkval = 594

In [51]:
bingo

true

In [20]:
additions = collect(0:length(bus_cycles)-1)
additions[1:maxidx] = reverse(collect(0:maxidx-1) .* -1)
additions[maxidx:end] = 0:length(additions)-maxidx
additions = collect(additions);

In [21]:
additions

4-element Array{Int64,1}:
 -3
 -2
 -1
  0

In [22]:
valid_indices = [idx for (idx, v) in enumerate(bus_cycles) if v != 0]

3-element Array{Int64,1}:
 1
 3
 4

In [24]:
valid_bus_cycles = bus_cycles[valid_indices]

3-element Array{Int64,1}:
 17
 13
 19

In [25]:
valid_additions = additions[valid_indices]

3-element Array{Int64,1}:
 -3
 -1
  0

In [26]:
valid_maxidx = argmax(valid_bus_cycles)
valid_maxval = valid_bus_cycles[valid_maxidx]

19

In [27]:
valid_bus_cycles

3-element Array{Int64,1}:
 17
 13
 19

In [28]:
valid_additions

3-element Array{Int64,1}:
 -3
 -1
  0

In [29]:
i = 1
while true
    checkval = valid_maxval * i
    checkvals = valid_additions .+ checkval
    bingo = true
    for (jidx, j) in enumerate(valid_bus_cycles)
        if checkvals[jidx] % j != 0
            bingo = false
            break
        end
    end
    if bingo
        println(checkval)
        println(checkvals)
        break
    end
    i += 1
end

3420
[3417, 3419, 3420]


In [215]:
?lcm

search: lcm selectdim colorschemes colorscheme! test_colorscheme



```
lcm(x,y)
```

Least common (non-negative) multiple. The arguments may be integer and rational numbers.

!!! compat "Julia 1.4"
    Rational arguments require Julia 1.4 or later.


# Examples

```jldoctest
julia> lcm(2,3)
6

julia> lcm(-2,3)
6

julia> lcm(0,3)
0

julia> lcm(0,0)
0

julia> lcm(1//3,2//3)
2//3

julia> lcm(1//3,-2//3)
2//3

julia> lcm(1//3,2)
2//1
```
